### ISSUE TITLE
amazon-vine.py no longer works :-(

### ISSUE THREAD

**Issue by HubbabbuH** [timur-tabi/amazon-vine#1]
As of around 5:30PM Pacific Time today, I noticed that the amazon-vine script no longer works, and always just returns 0 items for both "Your Queue" and "Vine for All". Can you please fix this? Thanks!!!!

**Comment by timur-tabi** [comment]
It looks like Amazon is catching on to my script.  It's rejecting the user-agent string.  I'm going to have to add a user-agent randomizer.  In the meantime, just use a different string on line 43.

**Comment by User2020** [comment]
I changed my agent string a long time ago and mine is still working.

**Comment by timur-tabi** [comment]
I've updated the script to use the fake_useragent package, which is a third-party package that needs to be manually installed.  I'm going to have to randomize other parts of the script to keep under Amazon's radar.
