### ISSUE TITLE
The sw stuck at "Waiting 10 minutes"

### ISSUE THREAD

**Issue by zyzzalando** [timur-tabi/amazon-vine#10]
I simply changed the URL for amazon italy.
The sw parse correctly all the items in list at boot but after it stuck at "waiting 10 minutes" and it do not check anymore the list (in fact when a new product appear it do not notify me anything).
![ddowcnhwsaarhvd jpg-large](https://user-images.githubusercontent.com/25319091/27783637-453571f8-5fd7-11e7-9cca-8760ea25603e.jpeg)

**Comment by timur-tabi** [comment]
Please give details about your OS and python version.

**Comment by zyzzalando** [comment]
As you can see is macOS 10.12.5 and python 2.7.13

**Comment by timur-tabi** [comment]
I won't be able to look at this until next week, but as a temp fix, just add a "return False" in the asleep() function, right under the "global options" line.

Are you connecting to you Mac via ssh or remote desktop?  The reason you see this is because asleep_mac() thinks that your monitor has been turned off, or that it's running under a different user. I suspect that code no longer works in 10.12.

**Comment by zyzzalando** [comment]
Ok, I have just deleted all the asleep() body and I left only "Return false" but the script close itself after the first parsing.
I log in my Mac physically and I use the terminal to run the script.

**Comment by zyzzalando** [comment]
![schermata 2017-07-03 alle 15 43 25](https://user-images.githubusercontent.com/25319091/27795436-6b8e69d4-6006-11e7-9ce4-5748abb34f84.png)

**Comment by zyzzalando** [comment]
however the number of item in vine list is correct but the number of item in vine for all list it's totally incorrect

**Comment by timur-tabi** [comment]
I will need to add some more debugging code to help me debug this.  In the meantime, can you give me the output of the "pmset -g" command?

**Comment by zyzzalando** [comment]
pmset -g
System-wide power settings:
Currently in use:
 standby              0
 Sleep On Power Button 1
 womp                 1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 powernap             1
 autorestart          0
 networkoversleep     0
 disksleep            0
 sleep                0
 autopoweroffdelay    28800
 hibernatemode        0
 autopoweroff         0
 ttyskeepawake        1
 displaysleep         10
 standbydelay         10800



THANKS A LOT FOR THE HELP, ANYWAY :)

**Comment by timur-tabi** [comment]
Ok, looks like I have my work cut out for me next week.

**Comment by zyzzalando** [comment]
Hi timur,
I'm sorry to bother you but did you find a fix for this annoying problem?

**Comment by timur-tabi** [comment]
Sorry, I haven't had a chance to look at it.  Note that the script looks for a lot of English text when it downloads pages.  It's not going to work on Amazon.it without some hackery, and I don't think I can support multiple languages that well. I can fix the 10-minute timeout problem, but the login problem will be tricky.

**Comment by zyzzalando** [comment]
Yeah, do not worry I am especially interested in the fix of the 10-minute timeout problem.

**Comment by timur-tabi** [comment]
Can you post the output of this command:
`pmset -g powerstate AppleDisplay`

**Comment by zyzzalando** [comment]
of course ! as I said my mac is an iMac Late 2013 27-inch

pmset -g powerstate AppleDisplay

      Driver ID  Current State  Max State  Current State Description
Internal failure: Failed to get power state information

**Comment by timur-tabi** [comment]
Ok, I guess you don't actually have an AppleDisplay, which seems weird since it's an iMac.  Ok, can you send me the output of:
`pmset -g powerstate`

**Comment by zyzzalando** [comment]
pmset -g powerstate

      Driver ID  Current State  Max State  Current State Description
IOPMrootDomain              3          3  ON
AppleFDEKeyStore            1          1  ON
AppleACPIPCI                3          3  ON
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
AppleBacklightDisplay       3          3  USEABLE
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAHDMI_DPDriver       1          1  USEABLE
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           3          3  USEABLE
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           3          3  USEABLE
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           3          3  USEABLE
BroadcomBluetoothHostCon    2          2  USEABLE
AppleIntelMEIDriver         1          1  ON
AppleMEClientController     1          1  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAHDMI_DPDriver       1          1  USEABLE
AppleHDADriver              1          1  USEABLE
BCM5701Enet                 2          2  ON,USEABLE
AppleThunderboltHAL         0          0  None
IOThunderboltController     0          0  None
IOThunderboltSwitchType2    0          0  None
AppleThunderboltDPOutAda    0          0  None
AppleThunderboltEDMSink     0          0  None
AppleLPC                    1          1  USEABLE
AppleIntelPchSeriesAHCI     2          2  USEABLE
AppleSMBusControllerICH     1          1  USEABLE
AppleMikeyDriver            2          2  USEABLE
AppleSMC                    1          1  USEABLE
AppleLMUController          1          1  ON
AppleRTC                    2          2  None
AppleUSBLegacyRoot          4          4  USEABLE
X86PlatformPlugin           1          1  USEABLE
AppleSSE                    1          1  ON
IODisplayWrangler           4          4  USEABLE
AppleHSBluetoothDevice      1          1  USEABLE
AppleHSBluetoothDevice      1          1  USEABLE
AppleHSBluetoothDevice      1          1  USEABLE
AppleHSBluetoothDevice      1          1  USEABLE

**Comment by timur-tabi** [comment]
Ok, one more experiment.  Can you repeat the above command, but with your monitor turned off?  Just type in the command, turn off the monitor, and press enter.  Then turn on the monitor and paste the output here.

I suspect that there will be a different value for AppleBacklightDisplay

**Comment by zyzzalando** [comment]
in the iMac when I press enter the monitor turn on automatically, so it is not possible !

**Comment by timur-tabi** [comment]
Ok try this.  Type in the following command, press enter, turn off the monitor, and then wait 15 seconds.
`sleep 15 && pmset -g powerstate`

**Comment by zyzzalando** [comment]
Driver ID  Current State  Max State  Current State Description
IOPMrootDomain              3          3  ON
AppleFDEKeyStore            1          1  ON
AppleACPIPCI                3          3  ON
NVDA                        1          2  None
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
AppleBacklightDisplay       0          0  None
NVDA                        1          2  None
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
NVDA                        1          2  None
NVDA                        2          2  USEABLE
NVDA                        2          2  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAHDMI_DPDriver       1          1  USEABLE
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           3          3  USEABLE
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           3          3  USEABLE
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           1          3  LOW_POWER
AppleUSB20HubPort           3          3  USEABLE
BroadcomBluetoothHostCon    2          2  USEABLE
AppleIntelMEIDriver         1          1  ON
AppleMEClientController     1          1  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAController          2          2  USEABLE
AppleHDAHDMI_DPDriver       1          1  USEABLE
AppleHDADriver              1          1  USEABLE
BCM5701Enet                 2          2  ON,USEABLE
AppleThunderboltHAL         0          0  None
IOThunderboltController     0          0  None
IOThunderboltSwitchType2    0          0  None
AppleThunderboltDPOutAda    0          0  None
AppleThunderboltEDMSink     0          0  None
AppleLPC                    1          1  USEABLE
AppleIntelPchSeriesAHCI     2          2  USEABLE
AppleSMBusControllerICH     1          1  USEABLE
AppleMikeyDriver            2          2  USEABLE
AppleSMC                    1          1  USEABLE
AppleLMUController          1          1  ON
AppleRTC                    2          2  None
AppleUSBLegacyRoot          4          4  USEABLE
X86PlatformPlugin           1          1  USEABLE
AppleSSE                    1          1  ON
IODisplayWrangler           1          4  None
AppleHSBluetoothDevice      1          1  USEABLE
AppleHSBluetoothDevice      1          1  USEABLE
AppleHSBluetoothDevice      1          1  USEABLE
AppleHSBluetoothDevice      1          1  USEABLE

**Comment by timur-tabi** [comment]
Ok, thanks.  In this line:

`output = subprocess.check_output(['pmset','-g','powerstate','AppleDisplay'])`

Can you change _AppleDisplay_ to _AppleBacklightDisplay_?  It should then wait 10 minutes only when the monitor is off or asleep.  That is, you should not see the "Waiting 10 minutes" while the display is on, but if you turn off the display and then come back after 10-15 minutes, you should see the message.  The whole idea behind the feature is that the script does **not** check Amazon while you're not at the computer.

**Comment by zyzzalando** [comment]
I change it but it still do not work...
![schermata 2017-10-23 alle 19 07 49](https://user-images.githubusercontent.com/25319091/31902561-90cebc9a-b825-11e7-8068-c48e2aa99145.png)
![schermata 2017-10-23 alle 19 08 21](https://user-images.githubusercontent.com/25319091/31902574-937eb260-b825-11e7-8dc8-bea403cadeae.png)

**Comment by timur-tabi** [comment]
Sorry, can you change that line and next to this:

```
        output = subprocess.check_output(['pmset','-g','powerstate','AppleDisplay','AppleBacklightDisplay'])
        m = re.search('^Apple.*Display.*USEABLE', output, re.MULTILINE)
```
Make sure you keep the lines indented the way they are now.  Python cares about how much a line is indented.

**Comment by zyzzalando** [comment]
now it works ! thank you very much timur !

**Comment by timur-tabi** [comment]
If you want me to add support for Amazon.it, open another ticket.  I will need your help to fix it, though.
