### ISSUE TITLE
General Error no control matching name 'password'

### ISSUE THREAD

**Issue by pbnelson** [timur-tabi/amazon-vine#13]
Starting 29NOV2017 I get `General Error no control matching name 'password'` when logging in with email/password, and also when logging in with --browser=firefox. Using --browser=chrome returns a different error: `sqlite3.OperationalError: no such column: encrypted_value` My hunch is that these problems are related to Amazon's recent push for two-step-verification. Last month I got the script to continue working by disabling two-step-verification, but now even that workaround has failed.

**Comment by timur-tabi** [comment]
Ugh.  I'll try to fix this before the end of the month.

**Comment by pbnelson** [comment]
Thanks! Since the end of the month is midnight tonight, that's awesome turnaround! Just kidding, I couldn't resist. I appreciate the work you put into this.

**Comment by pbnelson** [comment]
This problem apparently fixed itself. A short-term glitch at Amazon? In any case, it logs in today, and has shown me items from my personal queue as well as 'vine for all'.

**Comment by timur-tabi** [comment]
Like I always say, don't fix today what won't break until tomorrow.  However, I'm still seeing the double login pages, so it may still be an issue for some people.
