### ISSUE TITLE
Upgrading to Python 3, removing login

### ISSUE THREAD

**Issue by nothing-much-coder** [timur-tabi/amazon-vine#15]
Hi, thanks for the great work you put in! I've got it up and running with Python 3 and [poetry](https://github.com/sdispater/poetry) for managing dependencies. There are a lot of changes, mostly removing code, since the login isn't working anymore. I'm using the cookie method only. It has an issue or two, but it's working. Let me know if you want a PR. 

[My changes](https://github.com/codergator/amazon-vine/pull/1)

**Comment by timur-tabi** [comment]
I've lost access to Amazon Vine (been too lazy to finish my reviews), so I can't test the app.  And since I don't know Python 3, I would rather you keep your version as a separate fork.

**Comment by nothing-much-coder** [comment]
All right! Makes sense.
